---
version: "2.0"
services:
  tts:
    image: chicha21/tts:0.0.1
    expose:
      - port: 8081
        as: 8081
        to:
          - global: true
    env:
      - PORT=8081
profiles:
  compute:
    tts:
      resources:
        cpu:
          units: 2
        memory:
          size: 5Gi
        storage:
          - size: 10Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        chatbot:
          denom: uakt
          amount: 1000
deployment:
  tts:
    dcloud:
      profile: tts
      count: 1
